version: 0.1

phases:
  install:
    commands:
      
  build:
    commands:
      
  post_build:
    commands:
      - aws --region us-east-1 s3 sync ./src/ s3://mailexec.net/ --acl=public-read --delete